# Generated by entrypoint.sh. Add customizations under /etc/samba/conf.d.
#  DO NOT EDIT THIS FILE.

[global]
  netbios name = %NETBIOS_NAME%
  realm = %REALM%
  server role = active directory domain controller
  workgroup = %WORKGROUP%

  add machine script = /usr/sbin/adduser -D -H -G users -s /bin/false %u

  allow dns updates = %ALLOW_DNS_UPDATES%
  bind interfaces only = %BIND_INTERFACES_ONLY%
  domain logons = %DOMAIN_LOGONS%
  domain master = %DOMAIN_MASTER%
  interfaces = %INTERFACES%
  log level = %LOG_LEVEL%
  winbind refresh tickets = Yes
  # winbind trusted domains only = %WINBIND_TRUSTED_DOMAINS_ONLY%
  winbind use default domain = %WINBIND_USE_DEFAULT_DOMAIN%

  state directory = %SAMBA_TARGET_DIR%/state
  cache directory = %SAMBA_TARGET_DIR%/cache
  private dir     = %SAMBA_TARGET_DIR%/private

  #ttls enabled  = yes
  #ttls keyfile  = tls/key.pem
  #ttls certfile = tls/cert.pem
  #ttls cafile   = tls/ca.pem

  dns forwarder = 127.0.0.11



#  cache directory = /srv/cache
#  dns forwarder = 127.0.0.11
#  lock directory = /srv
#  log level = 0
#  netbios name = SAMBA4
#  private dir = /srv/private
#  realm = MATRIX.LAN
#  server role = active directory domain controller
#  state directory = /srv/state
#  workgroup = SMB
#  idmap_ldb:use rfc2307 = yes
