
FROM alpine:3.9

# ---------------------------------------------------------------------------------------

RUN \
  apk update  --quiet --no-cache && \
  apk upgrade --quiet --no-cache && \
  apk add     --quiet --no-cache \
    bash \
    ca-certificates \
    samba-client \
    openldap-clients && \
  rm -rf \
    /tmp/* \
    /var/cache/apk/*

ADD rootfs/ /
ADD tests/ /

CMD ["/tests.sh"]

# ---------------------------------------------------------------------------------------
