#!/bin/bash

# Custom build for Docker Hub
# see: https://medium.com/microscaling-systems/labelling-automated-builds-on-docker-hub-f3d073fb8e1

docker build \
  --file Dockerfile.test \
  --rm \
  --compress \
  --tag ${DOCKER_NAME_SPACE}/${DOCKER_IMAGE_NAME}-client .

